<a href="https://colab.research.google.com/github/kapuGayathri/New-Gqt/blob/main/scikit.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import sklearn

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
from sklearn.datasets import make_regression

In [ ]:
make_regression(n_samples=20,n_features=4)

(array([[ 0.89286205,  0.96072025,  0.31433058,  0.15158272],
        [ 1.19989615, -0.10289487, -1.68115531,  1.82310641],
        [ 1.43159089, -1.17779761,  2.04816508,  0.29643504],
        [ 0.71611401,  0.41087406,  0.79126011, -0.43401273],
        [-0.1809908 ,  0.24090391, -0.33243874, -0.78590962],
        [ 0.74185505,  1.33194698, -0.73251023,  1.44200937],
        [-0.44662563, -0.41791734,  0.52415065,  0.51592377],
        [-1.65384856,  0.05536525,  0.171075  , -0.5874129 ],
        [ 1.0351744 , -0.19817154, -0.85006842, -0.3753758 ],
        [-0.53609738, -0.41877103,  1.52183497, -0.86490396],
        [ 0.49514059,  0.01661233, -0.90311083, -1.96715366],
        [ 1.4924881 ,  0.42857763,  1.85030594, -0.70297887],
        [ 0.74024768,  1.13375591,  0.33424904,  0.64137085],
        [-0.40997232, -1.67629152, -0.71199037,  0.61261569],
        [ 1.59863282,  0.14726239,  0.33300419, -0.83861429],
        [-1.50939095,  0.53998197,  0.17803562, -0.70615505],
        [-0.75417671,  0.61609398, -0.4725932 , -0.79598651],
        [-0.13264026,  0.54360183, -0.35588496, -0.33384966],
        [-1.24552104,  0.82802012, -0.48559898, -0.41719549],
        [ 1.29725992, -0.23449406,  0.54170743,  1.22417205]]),
 array([  77.39769659,   82.39622217,  187.04870022,   41.32758951,
         -96.90756155,  127.42002805,   65.26479061,  -85.57501453,
         -70.69140697,    3.82003021, -233.21913667,  111.13593882,
         123.62041194,  -34.28996553,   -9.94319825,  -83.4333253 ,
        -115.91271159,  -49.53452626,  -90.59248348,  182.06930097]))

In [ ]:
make_regression(n_samples=20,n_features=4,bias=10.3,noise=1.8)

(array([[-0.13971567,  0.47242119, -1.98070473, -0.42336536],
        [ 0.41886989,  0.05318671,  0.35587436,  0.45441725],
        [-1.46767439, -1.35040318, -0.02872964,  0.19706311],
        [-0.13250069,  0.52271687, -1.28802401,  0.12397441],
        [ 0.81279591,  0.2715655 , -0.40502988,  0.96664947],
        [ 0.76876786,  2.59969559,  0.29908946,  0.43517363],
        [ 0.94042179, -0.96536661,  0.72473656, -0.78102171],
        [ 0.88963872, -0.46780663,  0.01949274,  1.41130788],
        [ 0.73672205,  0.46078912,  2.13661978, -1.20291951],
        [ 0.02257523, -0.47222146,  0.09979408, -0.57153052],
        [-0.79956195, -0.5798504 , -0.79862138,  0.37804121],
        [ 1.04307128,  1.76684222, -0.10031663, -1.00042221],
        [ 0.53515273,  1.12714333, -0.3287718 ,  0.83468756],
        [-1.18257072,  0.07210154,  0.98050084, -0.62470603],
        [-1.4237489 ,  0.08634296,  1.5972358 , -2.15322192],
        [-1.62997976,  0.2696935 , -0.71127246, -1.45119564],
        [ 0.83694383, -0.3445258 ,  0.01838553, -0.48671998],
        [ 0.28747112, -1.24462262,  0.92553648, -0.00876496],
        [ 0.5424134 , -1.53084133, -0.26285861, -0.98773784],
        [-0.52711815, -1.63572392,  1.22084602,  0.31330276]]),
 array([ -85.06442404,   60.56071112, -168.74122326,  -27.14747412,
          56.86838252,  294.85705121,   -0.69610337,   30.82855375,
         201.84587249,  -32.0262301 , -121.91423248,  188.90199819,
         125.2004101 ,   18.67808959,   26.37730034, -101.68774972,
           7.73293163,  -30.64886501, -132.0093569 ,  -77.36677535]))

In [ ]:
x = [10,20,30,40]

In [ ]:
a, b, c, d = [10,20,30,40]

In [ ]:
x,y = make_regression(n_samples=20,n_features=4,bias=10.3,noise=1.8)

In [ ]:
x.shape

(20, 4)

In [ ]:
y.shape

(20,)

In [ ]:
pd.DataFrame(x)

           0         1         2         3
0  -0.072848 -0.534350 -0.631900  1.345813
1   0.258915 -2.138778 -0.305408  0.241951
2  -0.668386 -2.353376  0.507670  1.180952
3   1.247594 -0.453892  2.110090 -0.177326
4   0.965988 -0.462554  2.092919  0.159676
5  -0.647375  0.931712 -0.782370 -0.402471
6  -0.400547 -2.760695 -0.077235 -1.136610
7  -0.355076 -0.038266  2.077360  0.074601
8   0.893837  0.090723  0.366740  0.802860
9   0.523125 -1.234275  0.282560 -2.706543
10  0.840278  0.209035  1.885967  0.550157
11 -0.251850 -0.485451 -2.886434 -1.735395
12  0.965514 -1.690902  1.377922  0.194314
13 -0.691907 -0.002296  1.627797 -0.320647
14 -1.627548 -0.265300 -1.538978 -0.815088
15 -0.920882  0.912471 -1.405336  0.858478
16  0.576809 -0.165252  0.533319 -1.306009
17 -1.614339  1.230970 -0.023304 -0.927603
18 -1.573313  0.283446  0.452468 -2.332965
19  0.465472  1.682418 -1.013891  0.931935

In [ ]:
df = pd.DataFrame(x).round(2)

In [ ]:
df

    col1  col2  col3  col4
0  -0.07 -0.53 -0.63  1.35
1   0.26 -2.14 -0.31  0.24
2  -0.67 -2.35  0.51  1.18
3   1.25 -0.45  2.11 -0.18
4   0.97 -0.46  2.09  0.16
5  -0.65  0.93 -0.78 -0.40
6  -0.40 -2.76 -0.08 -1.14
7  -0.36 -0.04  2.08  0.07
8   0.89  0.09  0.37  0.80
9   0.52 -1.23  0.28 -2.71
10  0.84  0.21  1.89  0.55
11 -0.25 -0.49 -2.89 -1.74
12  0.97 -1.69  1.38  0.19
13 -0.69 -0.00  1.63 -0.32
14 -1.63 -0.27 -1.54 -0.82
15 -0.92  0.91 -1.41  0.86
16  0.58 -0.17  0.53 -1.31
17 -1.61  1.23 -0.02 -0.93
18 -1.57  0.28  0.45 -2.33
19  0.47  1.68 -1.01  0.93

In [ ]:
df.columns = ["col1","col2","col3","col4"]

In [ ]:
df

    col1  col2  col3  col4
0  -0.07 -0.53 -0.63  1.35
1   0.26 -2.14 -0.31  0.24
2  -0.67 -2.35  0.51  1.18
3   1.25 -0.45  2.11 -0.18
4   0.97 -0.46  2.09  0.16
5  -0.65  0.93 -0.78 -0.40
6  -0.40 -2.76 -0.08 -1.14
7  -0.36 -0.04  2.08  0.07
8   0.89  0.09  0.37  0.80
9   0.52 -1.23  0.28 -2.71
10  0.84  0.21  1.89  0.55
11 -0.25 -0.49 -2.89 -1.74
12  0.97 -1.69  1.38  0.19
13 -0.69 -0.00  1.63 -0.32
14 -1.63 -0.27 -1.54 -0.82
15 -0.92  0.91 -1.41  0.86
16  0.58 -0.17  0.53 -1.31
17 -1.61  1.23 -0.02 -0.93
18 -1.57  0.28  0.45 -2.33
19  0.47  1.68 -1.01  0.93

In [ ]:
df.rename(columns={
    "col1":"delhi",
    "col2":"mumbai",
    "col3":"bangalore",
    "col4":"hyderabad"
},inplace=True)

In [ ]:
df

    delhi  mumbai  bangalore  hyderabad
0   -0.07   -0.53      -0.63       1.35
1    0.26   -2.14      -0.31       0.24
2   -0.67   -2.35       0.51       1.18
3    1.25   -0.45       2.11      -0.18
4    0.97   -0.46       2.09       0.16
5   -0.65    0.93      -0.78      -0.40
6   -0.40   -2.76      -0.08      -1.14
7   -0.36   -0.04       2.08       0.07
8    0.89    0.09       0.37       0.80
9    0.52   -1.23       0.28      -2.71
10   0.84    0.21       1.89       0.55
11  -0.25   -0.49      -2.89      -1.74
12   0.97   -1.69       1.38       0.19
13  -0.69   -0.00       1.63      -0.32
14  -1.63   -0.27      -1.54      -0.82
15  -0.92    0.91      -1.41       0.86
16   0.58   -0.17       0.53      -1.31
17  -1.61    1.23      -0.02      -0.93
18  -1.57    0.28       0.45      -2.33
19   0.47    1.68      -1.01       0.93

In [ ]:
pd.date_range("02-02-05",periods=10,freq="m")

/tmp/ipykernel_482/3357745405.py:1: FutureWarning: 'm' is deprecated and will be removed in a future version, please use 'ME' instead.
  pd.date_range("02-02-05",periods=10,freq="m")

DatetimeIndex(['2005-02-28', '2005-03-31', '2005-04-30', '2005-05-31',
               '2005-06-30', '2005-07-31', '2005-08-31', '2005-09-30',
               '2005-10-31', '2005-11-30'],
              dtype='datetime64[ns]', freq='ME')

In [ ]:
df.set_index(pd.date_range("02-02-05",periods=20,freq="d"),inplace=True)

In [ ]:
df

            delhi  mumbai  bangalore  hyderabad
2005-02-02  -0.07   -0.53      -0.63       1.35
2005-02-03   0.26   -2.14      -0.31       0.24
2005-02-04  -0.67   -2.35       0.51       1.18
2005-02-05   1.25   -0.45       2.11      -0.18
2005-02-06   0.97   -0.46       2.09       0.16
2005-02-07  -0.65    0.93      -0.78      -0.40
2005-02-08  -0.40   -2.76      -0.08      -1.14
2005-02-09  -0.36   -0.04       2.08       0.07
2005-02-10   0.89    0.09       0.37       0.80
2005-02-11   0.52   -1.23       0.28      -2.71
2005-02-12   0.84    0.21       1.89       0.55
2005-02-13  -0.25   -0.49      -2.89      -1.74
2005-02-14   0.97   -1.69       1.38       0.19
2005-02-15  -0.69   -0.00       1.63      -0.32
2005-02-16  -1.63   -0.27      -1.54      -0.82
2005-02-17  -0.92    0.91      -1.41       0.86
2005-02-18   0.58   -0.17       0.53      -1.31
2005-02-19  -1.61    1.23      -0.02      -0.93
2005-02-20  -1.57    0.28       0.45      -2.33
2005-02-21   0.47    1.68      -1.01       0.93

In [ ]:
df

            delhi  mumbai  bangalore  hyderabad
2005-02-02  -0.07   -0.53      -0.63       1.35
2005-02-03   0.26   -2.14      -0.31       0.24
2005-02-04  -0.67   -2.35       0.51       1.18
2005-02-05   1.25   -0.45       2.11      -0.18
2005-02-06   0.97   -0.46       2.09       0.16
2005-02-07  -0.65    0.93      -0.78      -0.40
2005-02-08  -0.40   -2.76      -0.08      -1.14
2005-02-09  -0.36   -0.04       2.08       0.07
2005-02-10   0.89    0.09       0.37       0.80
2005-02-11   0.52   -1.23       0.28      -2.71
2005-02-12   0.84    0.21       1.89       0.55
2005-02-13  -0.25   -0.49      -2.89      -1.74
2005-02-14   0.97   -1.69       1.38       0.19
2005-02-15  -0.69   -0.00       1.63      -0.32
2005-02-16  -1.63   -0.27      -1.54      -0.82
2005-02-17  -0.92    0.91      -1.41       0.86
2005-02-18   0.58   -0.17       0.53      -1.31
2005-02-19  -1.61    1.23      -0.02      -0.93
2005-02-20  -1.57    0.28       0.45      -2.33
2005-02-21   0.47    1.68      -1.01       0.93

In [ ]:
df.to_excel("regression.xlsx")

In [ ]:
pd.read_excel("regression2.xlsx")

   Unnamed: 0  delhi  mumbai  bangalore  hyderabad
0  2005-02-02  -0.07   -0.53      -0.63       1.35
1  2005-02-03   0.26   -2.14      -0.31       0.24
2  2005-02-04  -0.67   -2.35       0.51       1.18
3  2005-02-05   1.25   -0.45       2.11      -0.18
4  2005-02-06   0.97   -0.46       2.09       0.16
5  2005-02-07  -0.65    0.93      -0.78      -0.40
6  2005-02-08  -0.40   -2.76      -0.08      -1.14
7  2005-02-09  -0.36   -0.04       2.08       0.07
8  2005-02-10   0.89    0.09       0.37       0.80
9  2005-02-11   0.52   -1.23       0.28      -2.71
10 2005-02-12   0.84    0.21       1.89       0.55
11 2005-02-13  -0.25   -0.49      -2.89      -1.74
12 2005-02-14   0.97   -1.69       1.38       0.19
13 2005-02-15  -0.69    0.00       1.63      -0.32
14 2005-02-16  -1.63   -0.27      -1.54      -0.82
15 2005-02-17  -0.92    0.91      -1.41       0.86
16 2005-02-18   0.58   -0.17       0.53      -1.31
17 2005-02-19  -1.61    1.23      -0.02      -0.93
18 2005-02-20  -1.57    0.28       0.45      -2.33
19 2005-02-21   0.47    1.68      -1.01       0.93

In [ ]:
ndf = pd.read_excel("regression2.xlsx",index_col="Unnamed: 0")

In [ ]:
ndf

            delhi  mumbai  bangalore  hyderabad
2005-02-02  -0.07   -0.53      -0.63       1.35
2005-02-03   0.26   -2.14      -0.31       0.24
2005-02-04  -0.67   -2.35       0.51       1.18
2005-02-05   1.25   -0.45       2.11      -0.18
2005-02-06   0.97   -0.46       2.09       0.16
2005-02-07  -0.65    0.93      -0.78      -0.40
2005-02-08  -0.40   -2.76      -0.08      -1.14
2005-02-09  -0.36   -0.04       2.08       0.07
2005-02-10   0.89    0.09       0.37       0.80
2005-02-11   0.52   -1.23       0.28      -2.71
2005-02-12   0.84    0.21       1.89       0.55
2005-02-13  -0.25   -0.49      -2.89      -1.74
2005-02-14   0.97   -1.69       1.38       0.19
2005-02-15  -0.69    0.00       1.63      -0.32
2005-02-16  -1.63   -0.27      -1.54      -0.82
2005-02-17  -0.92    0.91      -1.41       0.86
2005-02-18   0.58   -0.17       0.53      -1.31
2005-02-19  -1.61    1.23      -0.02      -0.93
2005-02-20  -1.57    0.28       0.45      -2.33
2005-02-21   0.47    1.68      -1.01       0.93

In [ ]:
ndf.loc[:,"delhi"]

2005-02-02   -0.07
2005-02-03    0.26
2005-02-04   -0.67
2005-02-05    1.25
2005-02-06    0.97
2005-02-07   -0.65
2005-02-08   -0.40
2005-02-09   -0.36
2005-02-10    0.89
2005-02-11    0.52
2005-02-12    0.84
2005-02-13   -0.25
2005-02-14    0.97
2005-02-15   -0.69
2005-02-16   -1.63
2005-02-17   -0.92
2005-02-18    0.58
2005-02-19   -1.61
2005-02-20   -1.57
2005-02-21    0.47
Name: delhi, dtype: float64

In [ ]:
ndf[(ndf["delhi"]>0) & (ndf["mumbai"]>0)]

            delhi  mumbai  bangalore  hyderabad
2005-02-10   0.89    0.09       0.37       0.80
2005-02-12   0.84    0.21       1.89       0.55
2005-02-21   0.47    1.68      -1.01       0.93